apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: monitoring
spec:
  releaseName: external-dns
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/external-dns
    ref: master
    version: 2.5.3
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: values.yaml
      optional: false    
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: ../../flux/releases/gcp/dev/external-dns/env-values.yaml
      optional: false
