apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: example-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: issuer-dns01
  dnsNames:
  - prometheus.dev.k8s.managedkube.com
  - alertmanager.dev.k8s.managedkube.com
  - grafana.dev.k8s.managedkube.com