---
# Topology
topology:
  dns:
    type: Public
  masters: private
  nodes: private

api:
  # Sets the Master's API to Internal or Public
  # Docs: https://github.com/kubernetes/kops/blob/master/docs/topology.md#changing-topology-of-the-api-server
  loadBalancer:
    type: Internal

# etcd
etcd:
  version: 3.3.10

docker:
  overrides: false
  bridgeIP: 172.26.0.1/16

coreos:
  # Disables CoreOS auto update: https://github.com/kubernetes/kops/pull/4909
  disableAutoUpgrade: true