apiVersion: tests.testkube.io/v2
kind: Test
metadata:
  name: infra-prometheus-endpoint
  namespace: testkube
spec:
  content:
    data: |
      {
          "command": [
            "curl",
            "http://prometheus-operated.monitoring.svc:9090/-/ready"
          ],
          "expected_status": "200",
          "expected_body": "Prometheus is Ready."
      }
    type: string
  type: curl/test
